### Hadamard product

The Hadamard product (or entrywise product) is defined as:

\begin{equation}
\textbf{z} = \textbf{x} \circ \textbf{y} =
\begin{bmatrix}
x_1 y_1 \\ x_2 y_2 \\ \vdots \\ x_N y_N
\end{bmatrix}_{N \times 1}
\end{equation}

In [1]:
import numpy as np
import my_functions as mf

In [2]:
x = np.arange(5)
x

array([0, 1, 2, 3, 4])

In [3]:
y = np.arange(5,10)
y

array([5, 6, 7, 8, 9])

In [4]:
z = mf.hadamard(x,y)
z

array([ 0,  6, 14, 24, 36])

In [5]:
x*y

array([ 0,  6, 14, 24, 36])