In [1]:
import numpy as np

In [2]:
N = 3

In [4]:
A = np.reshape(np.random.rand(N*N),(N,N))
A

array([[ 0.21083939,  0.37215341,  0.54023134],
       [ 0.4688673 ,  0.89317882,  0.27804569],
       [ 0.384908  ,  0.04752286,  0.35079756]])

In [9]:
L1 = np.triu(A)
L1

array([[ 0.21083939,  0.37215341,  0.54023134],
       [ 0.        ,  0.89317882,  0.27804569],
       [ 0.        ,  0.        ,  0.35079756]])

In [7]:
B = np.reshape(np.random.rand(N*N),(N,N))
B

array([[ 0.20457617,  0.20349466,  0.55396302],
       [ 0.16318003,  0.8560349 ,  0.63522907],
       [ 0.54314111,  0.61355662,  0.3118658 ]])

In [10]:
L2 = np.triu(B)
L2

array([[ 0.20457617,  0.20349466,  0.55396302],
       [ 0.        ,  0.8560349 ,  0.63522907],
       [ 0.        ,  0.        ,  0.3118658 ]])

In [11]:
np.linalg.inv(L1)

array([[ 4.74294671, -1.97620426, -5.73782037],
       [ 0.        ,  1.11959663, -0.88740361],
       [ 0.        ,  0.        ,  2.85064699]])

In [12]:
np.linalg.inv(L2)

array([[ 4.88815487, -1.16200098, -6.31592256],
       [ 0.        ,  1.16817667, -2.37942022],
       [ 0.        ,  0.        ,  3.20650745]])