# Exemplos de vetores com diferentes shapes

Exemplifica como é o shape de diferentes numpy arrays.

## Importar módulos

In [1]:
import numpy as np

## Criar vetores

In [2]:
A1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
A1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [3]:
A1.shape

(3, 3)

In [4]:
np.mean(A1, axis=0)

array([ 4.,  5.,  6.])

In [5]:
A1.mean(axis=0)

array([ 4.,  5.,  6.])

In [6]:
np.mean(A1,axis=1)

array([ 2.,  5.,  8.])

In [7]:
np.mean(A1,axis=1).shape

(3,)

In [8]:
m1 = np.array([1,2,3])

In [9]:
m2 = np.array([[1],[2],[3]])

In [10]:
m1[1]

2

In [11]:
m2[1]

array([2])

In [12]:
m2[1][0]

2

## Preenchendo uma matriz

Jeito python de ser

In [15]:
a = range(1,10)
a = np.array(a)
a = np.reshape(a,(3,3))
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

ou

In [19]:
k = 1
A = np.zeros(9)
A = np.reshape(A,(3,3))
for i in range(3):
    for j in range(3):
        A[i][j] = k
        k = k + 1
A        

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.]])