### Principles of vector on python

##### Scalar vector multiplication

\begin{equation}
\mathbf{y} = a \mathbf{x} = a
\begin{bmatrix}
x_1 \\ x_2 \\ \cdots \\ x_N 
\end{bmatrix}
\end{equation}

In [1]:
import numpy as np

In [2]:
a = 0.5
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
y = a*x
y

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

##### Vector-vector addition

\begin{equation}
\mathbf{z} = \mathbf{x}+\mathbf{y} =
\begin{bmatrix}
x_1+y_1 \\ x_2+y_2 \\ \cdots \\ x_N+y_N
\end{bmatrix}
\end{equation}

In [4]:
x = np.arange(7)
print x
y = np.ones(7)*2
print y

[0 1 2 3 4 5 6]
[2. 2. 2. 2. 2. 2. 2.]


In [5]:
z = y + x
z

array([2., 3., 4., 5., 6., 7., 8.])

In [6]:
x = np.arange(10, 18)
x

array([10, 11, 12, 13, 14, 15, 16, 17])

In [7]:
x[3:6:1]

array([13, 14, 15])

In [8]:
x[3:7:1]

array([13, 14, 15, 16])