## Matrix and vector operations

Calculate vector $N \times 1$ vector $\mathbf{y}$ through matrix-vector product as in
\begin{equation}
\mathbf{y} = \mathbf{A} \mathbf{x}
\end{equation}

where
\begin{equation}
\mathbf{A} =
\begin{bmatrix}
a_{11} & \cdots & a_{1M} \\
\vdots &  & \vdots \\
a_{N1} & \cdots & a_{NM}
\end{bmatrix}_{N \times M} =
\begin{bmatrix}
A[1,:] \\
\vdots \\
A[N,:]
\end{bmatrix}_{N \times M} =
\begin{bmatrix}
A[:,1] & \cdots & A[:,M]
\end{bmatrix}_{N \times M}
\end{equation}

and $\mathbf{x}$ is a $M \times 1$ vector.

In [1]:
import numpy as np
import my_functions as mf

### Exercise 1

In [2]:
A = np.array([[1,2,3], [4,5,6],[7,8,9]])
print A, A.shape

[[1 2 3]
 [4 5 6]
 [7 8 9]] (3, 3)


In [3]:
x = np.ones(3)
print x, x.shape

[1. 1. 1.] (3,)


In [4]:
y = np.zeros_like(x)
y

array([0., 0., 0.])

In [5]:
print A, x

[[1 2 3]
 [4 5 6]
 [7 8 9]] [1. 1. 1.]


In [6]:
N = 3
M = 3
print 'i', 'j', 'y'
for i in range(N):
    for j in range(M):
        y[i] += A[i,j]*x[j]
        print i,j,y
print y.shape

i j y
0 0 [1. 0. 0.]
0 1 [3. 0. 0.]
0 2 [6. 0. 0.]
1 0 [6. 4. 0.]
1 1 [6. 9. 0.]
1 2 [ 6. 15.  0.]
2 0 [ 6. 15.  7.]
2 1 [ 6. 15. 15.]
2 2 [ 6. 15. 24.]
(3,)


In [7]:
y = mf.matvec_prod1(A, x)
y

array([ 6., 15., 24.])

In [8]:
y = np.zeros_like(x)
print 'A', 'x'
for i in range(N):
    print A[i,:], x
    y[i] = np.dot(A[i,:],x)
    print i,y
# print y, y.shape

A x
[1 2 3] [1. 1. 1.]
0 [6. 0. 0.]
[4 5 6] [1. 1. 1.]
1 [ 6. 15.  0.]
[7 8 9] [1. 1. 1.]
2 [ 6. 15. 24.]


In [9]:
y = mf.matvec_prod2(A, x)
y

array([ 6., 15., 24.])

In [10]:
y = np.zeros_like(x)
print 'A', 'x'
for j in range(M):
    print A[:,j], x[j]
    y += A[:,j]*x[j]
    print j,y
# print y, y.shape

A x
[1 4 7] 1.0
0 [1. 4. 7.]
[2 5 8] 1.0
1 [ 3.  9. 15.]
[3 6 9] 1.0
2 [ 6. 15. 24.]


In [11]:
y = mf.matvec_prod3(A, x)
y

array([ 6., 15., 24.])

### Exercise 2

In [12]:
N = 5 # number of data
ws = 3 # window size
i0 = ws//2
A = np.array(np.hstack( ( (1./ws)*np.ones(ws), np.zeros(N - ws + 1) ) ) )

In [13]:
(1./ws)*np.ones(ws)

array([0.33333333, 0.33333333, 0.33333333])

In [14]:
np.zeros(N - ws + 1)

array([0., 0., 0.])

In [15]:
np.hstack( ( (1./ws)*np.ones(ws), np.zeros(N - ws + 1) ) )

array([0.33333333, 0.33333333, 0.33333333, 0.        , 0.        ,
       0.        ])

In [16]:
A = np.array(np.hstack( ( (1./ws)*np.ones(ws), np.zeros(N - ws + 1) ) ) )
A

array([0.33333333, 0.33333333, 0.33333333, 0.        , 0.        ,
       0.        ])

In [17]:
A = np.resize(A, (N-2*i0, N))
A

array([[0.33333333, 0.33333333, 0.33333333, 0.        , 0.        ],
       [0.        , 0.33333333, 0.33333333, 0.33333333, 0.        ],
       [0.        , 0.        , 0.33333333, 0.33333333, 0.33333333]])

In [18]:
(N-2*i0, N)

(3, 5)

In [19]:
A = np.vstack((np.zeros(N), A, np.zeros(N)))
A

array([[0.        , 0.        , 0.        , 0.        , 0.        ],
       [0.33333333, 0.33333333, 0.33333333, 0.        , 0.        ],
       [0.        , 0.33333333, 0.33333333, 0.33333333, 0.        ],
       [0.        , 0.        , 0.33333333, 0.33333333, 0.33333333],
       [0.        , 0.        , 0.        , 0.        , 0.        ]])

In [20]:
A = np.array(np.hstack(((1./ws)*np.ones(ws), np.zeros(N - ws + 1))))
A = np.resize(A, (N-2*i0, N))
A = np.vstack((np.zeros(N), A, np.zeros(N)))

In [21]:
A

array([[0.        , 0.        , 0.        , 0.        , 0.        ],
       [0.33333333, 0.33333333, 0.33333333, 0.        , 0.        ],
       [0.        , 0.33333333, 0.33333333, 0.33333333, 0.        ],
       [0.        , 0.        , 0.33333333, 0.33333333, 0.33333333],
       [0.        , 0.        , 0.        , 0.        , 0.        ]])

In [22]:
# x = np.random.randint(100, 400, size=18)
np.random.random()
filt = mf.mat_sma(x, 3)
print x
print filt

[1. 1. 1.]
[0. 1. 0.]


### Exercise 3

In [23]:
spacing = 2.*np.pi/1000.
theta = np.arange(0., 2*np.pi, spacing)
theta.size

1000

In [24]:
y = np.sin(theta)

In [25]:
z_true = np.cos(theta)
z_true[995:]

array([0.99950656, 0.99968419, 0.99982235, 0.99992104, 0.99998026])

In [26]:
z_calc = mf.deriv1d(y, spacing)
z_calc[995:]

array([0.99949998, 0.99967761, 0.99981577, 0.99991447, 0.        ])