## Product of two matrices

Let $\mathbf{A}$ and $\mathbf{B}$ be, respectively, $N \times M$ and $M \times L$ matrices. These matrices can be represented *element-by-element*, by using a row partition or by using a column partition as follows:

\begin{equation}
\mathbf{A} =
\begin{bmatrix}
a_{11} & \cdots & a_{1M} \\
\vdots &  & \vdots \\
a_{N1} & \cdots & a_{NM}
\end{bmatrix}_{N \times M} =
\begin{bmatrix}
A[1,:] \\
\vdots \\
A[N,:]
\end{bmatrix}_{N \times M} =
\begin{bmatrix}
A[:,1] & \cdots & A[:,M]
\end{bmatrix}_{N \times M}
\end{equation}

and \begin{equation}
\mathbf{B} =
\begin{bmatrix}
b_{11} & \cdots & b_{1L} \\
\vdots &  & \vdots \\
b_{M1} & \cdots & b_{ML}
\end{bmatrix}_{M \times L} =
\begin{bmatrix}
B[1,:] \\
\vdots \\
B[M,:]
\end{bmatrix}_{M \times L} =
\begin{bmatrix}
B[:,1] & \cdots & B[:,L]
\end{bmatrix}_{M \times L}
\end{equation}

where $a_{ij} = \mathbf{A}[i,j]$ and $b_{ij} = \mathbf{B}[i,j]$, $i=1,\cdots,N$, $j=1,\cdots,M$ and $k=1,\cdots,L$.

Let $\mathbf{C}$ be a $N \times L$ matrix given by:
\begin{equation}
\mathbf{C} = \mathbf{A} \mathbf{B} \qquad ,
\end{equation}
with elements $cij=C[i,k]$, $i=1,\cdots,N$ and $k=1,\cdots,L$, defined as follows:

\begin{equation}
\mathbf{C} =
\begin{bmatrix}
c_{11} & \cdots & c_{1L} \\
\vdots &  & \vdots \\
c_{N1} & \cdots & c_{NL}
\end{bmatrix}_{N \times L} =
\begin{bmatrix}
(a_{11}b_{11}+\cdots+a_{1M}b_{M1}) & \cdots & (a_{11}b_{1L}+\cdots+a_{1M}b_{ML}) \\
\vdots & \vdots & \vdots \\
(a_{N1}b_{11}+\cdots+a_{NM}b_{M1}) & \cdots & (a_{N1}b_{1L}+\cdots+a_{NM}b_{ML})
\end{bmatrix}_{N \times L}
\end{equation}

In [1]:
import numpy as np
import my_functions as mf

In [2]:
A = np.array([[1,3],[2,4],[5,6]])
B = np.array([[1,2,0],[2,3,4]])
print A.shape
print B.shape

(3, 2)
(2, 3)


In [3]:
C1 = mf.matmat_prod1(A, B)
C1

array([[ 7., 11., 12.],
       [10., 16., 16.],
       [17., 28., 24.]])

In [4]:
C2 = mf.matmat_prod2(A, B)
C2

array([[ 7., 11., 12.],
       [10., 16., 16.],
       [17., 28., 24.]])

In [5]:
print A.shape, B.shape

(3, 2) (2, 3)


In [6]:
# C = np.zeros((B.shape[1], A.shape[0]))
C = np.zeros((A.shape[0], B.shape[1]))
for i in range(A.shape[0]):
    print np.dot(A[i,:],B), np.dot(A[i,:],B).shape
C

[ 7 11 12] (3,)
[10 16 16] (3,)
[17 28 24] (3,)


array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [7]:
# C3 = mf.matmat_prod3(A, B)
# C3

In [8]:
theta = 0.
R1 = mf.R1(theta)
R1

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0., -0.,  1.]])

In [9]:
R2 = mf.R2(theta)
R2

array([[ 1.,  0., -0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [10]:
R3 = mf.R3(theta)
R3

array([[ 1.,  0.,  0.],
       [-0.,  1.,  0.],
       [ 0.,  1.,  1.]])

In [11]:
I = np.identity(3)
I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])