### Outer product

The Outer product is defined as:

\begin{equation}
\textbf{M} = \textbf{x} \otimes \textbf{y} = \textbf{x} \textbf{y}^{\top} =
\begin{bmatrix}
x_1 \textbf{y}^{\top} \\ x_2 \textbf{y}^{\top} \\ \vdots \\ x_N \textbf{y}^{\top}
\end{bmatrix}_{N \times M} = 
\begin{bmatrix}
y_1 \textbf{x} & \cdots & y_N \textbf{x}
\end{bmatrix}_{N \times M}
\end{equation}

In [1]:
import numpy as np
import my_functions as mf

In [2]:
x = np.arange(5)
x

array([0, 1, 2, 3, 4])

In [3]:
y = np.arange(5,12)
y

array([ 5,  6,  7,  8,  9, 10, 11])

In [4]:
# OR
M = np.empty((x.size,y.size))
for i in range(x.size):
    for j in range(y.size):
        M[i,j] = x[i]*y[j]
print M

[[ 0.  0.  0.  0.  0.  0.  0.]
 [ 5.  6.  7.  8.  9. 10. 11.]
 [10. 12. 14. 16. 18. 20. 22.]
 [15. 18. 21. 24. 27. 30. 33.]
 [20. 24. 28. 32. 36. 40. 44.]]


In [5]:
# OR
M = np.empty((x.size,y.size))
for i in range(x.size):
    M[i,:] = x[i]*y
print M

[[ 0.  0.  0.  0.  0.  0.  0.]
 [ 5.  6.  7.  8.  9. 10. 11.]
 [10. 12. 14. 16. 18. 20. 22.]
 [15. 18. 21. 24. 27. 30. 33.]
 [20. 24. 28. 32. 36. 40. 44.]]


In [6]:
# OR
M = np.empty((x.size,y.size))
for j in range(y.size):
    M[:,j] = y[j]*x
print M

[[ 0.  0.  0.  0.  0.  0.  0.]
 [ 5.  6.  7.  8.  9. 10. 11.]
 [10. 12. 14. 16. 18. 20. 22.]
 [15. 18. 21. 24. 27. 30. 33.]
 [20. 24. 28. 32. 36. 40. 44.]]
