In [1]:
import numpy as np

In [2]:
A = np.array([[2.,1.,-1.],
              [-3.,-1.,2.],
              [-2.,1.,2.]])
A

array([[ 2.,  1., -1.],
       [-3., -1.,  2.],
       [-2.,  1.,  2.]])

In [3]:
y = np.array([8., -11., -3.])
y

array([  8., -11.,  -3.])

In [4]:
x = np.linalg.solve(A,y)
x

array([ 2.,  3., -1.])

### Steps 1 to 6

In [5]:
A1 = np.copy(A)
y1 = np.copy(y)

t12 = A[1,0]/A[0,0]    # step 1
A1[1,:] -= t12*A[0,:]  # step 2
y1[1] -= t12*y[0]      # step 3

t13 = A[2,0]/A[0,0]    # step 4
A1[2,:] -= t13*A[0,:]  # step 5
y1[2] -= t13*y[0]      # step 6

In [6]:
print A1

[[ 2.   1.  -1. ]
 [ 0.   0.5  0.5]
 [ 0.   2.   1. ]]


In [7]:
print y1

[8. 1. 5.]


### Steps 1 to 6 of the new matrix $A^{(1)}$

In [8]:
A2 = np.copy(A1)
y2 = np.copy(y1)

t23 = A1[2,1]/A1[1,1]  # step 1
A2[2,:] -= t23*A1[1,:]  # step 2
y2[2] -= t23*y1[1]      # step 3

In [9]:
print A2

[[ 2.   1.  -1. ]
 [ 0.   0.5  0.5]
 [ 0.   0.  -1. ]]


In [10]:
print y2

[8. 1. 1.]


In [11]:
xeq = np.linalg.solve(A2,y2)
print xeq
print '\n'
print x

[ 2.  3. -1.]


[ 2.  3. -1.]


### Code from the bottom of text

In [12]:
I = np.identity(3)

#### Iteration $k=1$:

In [13]:
u = np.array([1., 0., 0.])
u

array([1., 0., 0.])

In [14]:
t = np.array([0., A[1][0]/A[0][0], A[2][0]/A[0][0]])
t

array([ 0. , -1.5, -1. ])

In [15]:
print np.outer(t, u)
A1 = (I - np.outer(t, u)).dot(A)
A1

[[ 0.   0.   0. ]
 [-1.5 -0.  -0. ]
 [-1.  -0.  -0. ]]


array([[ 2. ,  1. , -1. ],
       [ 0. ,  0.5,  0.5],
       [ 0. ,  2. ,  1. ]])

In [16]:
y1 = (I - np.outer(t, u)).dot(y)
y1

array([8., 1., 5.])

#### Iteration $k=2$:

In [17]:
u = np.array([0., 1., 0.])
u

array([0., 1., 0.])

In [18]:
t = np.array([0., 0., A1[2][1]/A1[1][1]])
t

array([0., 0., 4.])

In [19]:
print np.outer(t, u)
B = (I - np.outer(t, u)).dot(A1)
B

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 4. 0.]]


array([[ 2. ,  1. , -1. ],
       [ 0. ,  0.5,  0.5],
       [ 0. ,  0. , -1. ]])

In [20]:
z = (I - np.outer(t, u)).dot(y1)
z

array([8., 1., 1.])

In [21]:
print np.linalg.solve(B,z)
print np.linalg.solve(A,y)

[ 2.  3. -1.]
[ 2.  3. -1.]
