## Product of two matrices

Let $\mathbf{A}$ and $\mathbf{B}$ be, respectively, $N \times M$ and $L \times P$ matrices given by:

\begin{equation}
\mathbf{A} =
\begin{bmatrix}
a_{11} & \cdots & a_{1M} \\
\vdots &  & \vdots \\
a_{N1} & \cdots & a_{NM}
\end{bmatrix}_{N \times M}
\end{equation}

and

\begin{equation}
\mathbf{B} =
\begin{bmatrix}
b_{11} & \cdots & b_{1P} \\
\vdots &  & \vdots \\
b_{L1} & \cdots & b_{LP}
\end{bmatrix}_{L \times P}
\end{equation}

The `Kronecker product` of $\mathbf{A}$ and $\mathbf{B}$, denoted as $\mathbf{A} \otimes \mathbf{B}$, is an $NL \times MP$ matrix given by:

\begin{equation}
\mathbf{A} \otimes \mathbf{B} =
\begin{bmatrix}
a_{11}\mathbf{B} & \cdots & a_{1M}\mathbf{B} \\
\vdots &  & \vdots \\
a_{N1}\mathbf{B} & \cdots & a_{NM}\mathbf{B}
\end{bmatrix}_{NL \times MP}
\end{equation}.

Notice that $\mathbf{A} \otimes \mathbf{B}$ is block matrix formed by $N \times M$ blocks, each one with $L \times P$ elements.

In [1]:
import numpy as np
import my_functions as mf

In [2]:
A = np.array([[1,3],[2,4],[5,6]])
B = np.array([[1,2,0],[2,3,4]])
print A.shape
print B.shape

(3, 2)
(2, 3)


In [3]:
C1 = mf.matmat_prod1(A, B)
C1

array([[ 7., 11., 12.],
       [10., 16., 16.],
       [17., 28., 24.]])

In [4]:
C2 = mf.matmat_prod2(A, B)
C2

array([[ 7., 11., 12.],
       [10., 16., 16.],
       [17., 28., 24.]])

In [5]:
C3 = mf.matmat_prod3(A, B)
C3

array([[ 7., 11., 12.],
       [10., 16., 16.],
       [17., 28., 24.]])

In [6]:
C4 = mf.matmat_prod4(A, B)
C4

array([[ 7., 11., 12.],
       [10., 16., 16.],
       [17., 28., 24.]])

In [7]:
# C5 = mf.matmat_prod5(A, B)
# C5

### Exercise 2

In [8]:
theta = 0.
R1 = mf.R1(theta)
R1

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0., -0.,  1.]])

In [9]:
R2 = mf.R2(theta)
R2

array([[ 1.,  0., -0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [10]:
R3 = mf.R3(theta)
R3

array([[ 1.,  0.,  0.],
       [-0.,  1.,  0.],
       [ 0.,  1.,  1.]])

In [11]:
I = np.identity(3)
I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])