In [1]:
import numpy as np
import my_functions as mf

In [2]:
I = np.identity(4)
I

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [3]:
# EXCHANGE PERMUTATION
Exc = np.copy(I[3::-1,:])
Exc

array([[0., 0., 0., 1.],
       [0., 0., 1., 0.],
       [0., 1., 0., 0.],
       [1., 0., 0., 0.]])

In [4]:
# DOWNSHIFT PERMUTATION
D1 = np.zeros((4,4))
D1[1:,:] = I[:3,:]
D1[0,:] = I[3,:]
print D1

[[0. 0. 0. 1.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]


In [5]:
# UPSHIFT PERMUTATION
U1 = np.zeros((4,4))
U1[0:3,:] = I[1:,:]
U1[3,:] = I[0,:]
print U1

[[0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [1. 0. 0. 0.]]


1) Are the matrices orthogonal?

In [6]:
print 'Exc*Exc.T =', np.dot(Exc, Exc.T)
print 'Exc.T*Exc =', np.dot(Exc.T, Exc)

Exc*Exc.T = [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
Exc.T*Exc = [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [7]:
print 'D1*D1.T =', np.dot(D1, D1.T)
print 'D1.T*D1 =', np.dot(D1.T, D1)

D1*D1.T = [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
D1.T*D1 = [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [8]:
print 'U1*U1.T =', np.dot(U1, U1.T)
print 'U1.T*U1 =', np.dot(U1.T, U1)

U1*U1.T = [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
U1.T*U1 = [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
