### Diagonal matrices - Part 1

In [1]:
import numpy as np
import my_functions as mf
import numpy.testing as npt

In [2]:
D = np.identity(5)*4.
D

array([[4., 0., 0., 0., 0.],
       [0., 4., 0., 0., 0.],
       [0., 0., 4., 0., 0.],
       [0., 0., 0., 4., 0.],
       [0., 0., 0., 0., 4.]])

In [3]:
x = np.arange(-2,3)
x

array([-2, -1,  0,  1,  2])

In [4]:
prod = mf.matvec_diag_prod(np.diag(D), x)
prod

array([-8., -4.,  0.,  4.,  8.])

In [5]:
# Test 1
true = np.array([-8., -4.,  0.,  4.,  8.])
D = np.identity(5)*4.
x = np.arange(-2.,3.)
calc = mf.matvec_diag_prod(np.diag(D), x)
npt.assert_almost_equal(calc, true, decimal=15)

In [6]:
# Test 2
d = np.random.rand(5)
x = np.arange(-2.,3.)
diag_prod = mf.matvec_diag_prod(d, x)

In [7]:
D = np.diag(d)
print D

[[0.87757209 0.         0.         0.         0.        ]
 [0.         0.54712272 0.         0.         0.        ]
 [0.         0.         0.39065396 0.         0.        ]
 [0.         0.         0.         0.96720298 0.        ]
 [0.         0.         0.         0.         0.12466517]]


In [8]:
print d
print diag_prod

[0.87757209 0.54712272 0.39065396 0.96720298 0.12466517]
[-1.75514419 -0.54712272  0.          0.96720298  0.24933033]


In [9]:
matvec = mf.matvec_prod1(D, x)
matvec

array([-1.75514419, -0.54712272,  0.        ,  0.96720298,  0.24933033])

In [10]:
y = np.zeros_like(x)
# print 'y[i]', 'D[i,j]','x[j]'
for i in range(D.shape[0]):
    for j in range(x.size):
        y[i] += D[i,j]*x[j]
#         print y[i], D[i,j], x[j]

In [11]:
print y

[-1.75514419 -0.54712272  0.          0.96720298  0.24933033]


In [12]:
npt.assert_almost_equal(matvec, diag_prod, decimal=15)

In [13]:
B = np.array([[1,2],[2,3]])
d = np.diag(np.identity(2))
C = mf.matmat_diagfull_prod(d, B)
C

array([[1, 2],
       [2, 3]])

In [14]:
E = mf.matmat_fulldiag_prod(B, d)
E

array([[1, 2],
       [2, 3]])