### Diagonal matrices - Part 2

In [1]:
import numpy as np
import my_functions as mf
import numpy.testing as npt

In [2]:
k = 3
x = np.array([1.,2.,1.,4.,6.])
print x

[1. 2. 1. 4. 6.]


In [3]:
x[k:]

array([4., 6.])

In [4]:
d = np.ones(x.size-np.abs(k))
print d

[1. 1.]


In [5]:
# for k < 0
# z = np.ones(x.size)
# z[:np.abs(k)] = np.zeros(np.abs(k))
# z[np.abs(k):] = mf.hadamard(d, x[:k])
# z
# for k = 0
# z = mf.hadamard(d, x)
# z

# for k > 0
# z = np.zeros(x.size)
# z[:d.size] = mf.hadamard(d, x[k:])
# z[d.size+1:] = np.zeros(k)
# z

In [6]:
z = mf.matvec_diagk_prod(d, k, x)
z

array([4., 6., 0., 0., 0.])

In [7]:
k = 3
x = np.array([1.,2.,1.,4.,6.])
d = np.random.rand(x.size-np.abs(k))

D = np.diag(d)
D

array([[0.84479954, 0.        ],
       [0.        , 0.33283137]])

In [17]:
D = np.zeros((5,5))
for i in range(2):
    print i
    D[i, 3+i] = d[i]
D

0
1


array([[0.        , 0.        , 0.        , 0.84479954, 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.33283137],
       [0.        , 0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ]])