### Band matrices

Let's consider the following $5 \times 5$ matrix $\mathbf{B}$:

\begin{equation}
\mathbf{B} =
\begin{bmatrix}
b_{11} & b_{12} & b_{13} & 0 & 0 \\
b_{21} & b_{22} & b_{23} & b_{24} & 0 \\
0 & b_{32} & b_{33} & b_{34} & b_{35} \\
0 & 0 & b_{43} & b_{44} & b_{45} \\
0 & 0 & 0 & b_{54} & b_{55}
\end{bmatrix}
\end{equation}

which is called a band (banded) matrix. In this example, the diagonals $k=-1,0,1,2$ have non-null elements. The lower and upper limits of $k$ are defined as the *lower bandwidth* and *upper bandwidth* of $\mathbf{B}$.

In [1]:
import numpy as np
import numpy.testing as npt
import my_functions as mf

In [2]:
x = np.array([1.,2.,1.,4.,6.])
print x

[1. 2. 1. 4. 6.]


In [3]:
B = np.array([[5.,4.,3.,0.,0.],[4.,5.,4.,3.,0.],[0.,4.,5.,4.,3.],\
              [0.,0.,4.,5.,4.],[0.,0.,0.,4.,5.]])
B

array([[5., 4., 3., 0., 0.],
       [4., 5., 4., 3., 0.],
       [0., 4., 5., 4., 3.],
       [0., 0., 4., 5., 4.],
       [0., 0., 0., 4., 5.]])

In [4]:
# Using np.dot
y_dot = np.dot(B, x)
y_dot

array([16., 30., 47., 48., 46.])

### MY CODE

In [5]:
b = np.reshape(B,(B.shape[0]*B.shape[1]))
ind = np.where(b==0)[0]
b = np.delete(b, ind)[b.size::-1]
print b, b.size

[5. 4. 4. 5. 4. 3. 4. 5. 4. 3. 4. 5. 4. 3. 4. 5.] 16


In [6]:
B1 = np.array([[0.,0.,0.,0.,0.],[4.,0.,0.,0.,0.],[0.,4.,0.,0.,0.],\
              [0.,0.,4.,0.,0.],[0.,0.,0.,4.,0.]])
print B1
b1 = np.reshape(B1,(B1.shape[0]*B1.shape[1]))
ind = np.where(b1==0)[0]
b1 = np.delete(b1, ind)[b1.size::-1]
print b1, b1.size

[[0. 0. 0. 0. 0.]
 [4. 0. 0. 0. 0.]
 [0. 4. 0. 0. 0.]
 [0. 0. 4. 0. 0.]
 [0. 0. 0. 4. 0.]]
[4. 4. 4. 4.] 4


In [7]:
B2 = np.array([[5.,0.,0.,0.,0.],[0.,5.,0.,0.,0.],[0.,0.,5.,0.,0.],\
               [0.,0.,0.,5.,0.],[0.,0.,0.,0.,5.]])
print B2
b2 = np.reshape(B2,(B2.shape[0]*B2.shape[1]))
ind = np.where(b2==0)[0]
b2 = np.delete(b2, ind)[b2.size::-1]
print b2, b2.size

[[5. 0. 0. 0. 0.]
 [0. 5. 0. 0. 0.]
 [0. 0. 5. 0. 0.]
 [0. 0. 0. 5. 0.]
 [0. 0. 0. 0. 5.]]
[5. 5. 5. 5. 5.] 5


In [8]:
B3 = np.array([[0.,0.,0.,0.,0.],[4.,0.,0.,0.,0.],[0.,4.,0.,0.,0.],\
              [0.,0.,4.,0.,0.],[0.,0.,0.,4.,0.]])
print B3
b3 = np.reshape(B3,(B3.shape[0]*B3.shape[1]))
ind = np.where(b3==0)[0]
b3 = np.delete(b3, ind)[b3.size::-1]
print b3, b3.size

[[0. 0. 0. 0. 0.]
 [4. 0. 0. 0. 0.]
 [0. 4. 0. 0. 0.]
 [0. 0. 4. 0. 0.]
 [0. 0. 0. 4. 0.]]
[4. 4. 4. 4.] 4


In [9]:
B4 = np.array([[0.,0.,3.,0.,0.],[0.,0.,0.,3.,0.],[0.,0.,0.,0.,3.],\
              [0.,0.,0.,0.,0.],[0.,0.,0.,0.,0.]])
print B4
b4 = np.reshape(B4,(B4.shape[0]*B4.shape[1]))
ind = np.where(b4==0)[0]
b4 = np.delete(b4, ind)[b4.size::-1]
print b4, b4.size

[[0. 0. 3. 0. 0.]
 [0. 0. 0. 3. 0.]
 [0. 0. 0. 0. 3.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[3. 3. 3.] 3


In [10]:
b = np.concatenate((b1,b2,b3,b4))
print b

[4. 4. 4. 4. 5. 5. 5. 5. 5. 4. 4. 4. 4. 3. 3. 3.]


In [11]:
# j1 = 0
# j2 = 4
# # y = mf.matvec_diagk_prod(b[j1:j2], -2, x)
# for i in range(-1,3):
#     if i < 0:
#         print i, j1, j2, b[j1:j2]
#         y += mf.matvec_diagk_prod(b[j1:j2], i, x)
#         j1 = j2
#         j2 += x.size+i
#     else:
#         y += mf.matvec_diagk_prod(b[j1:j2], i, x)
#         j1 = j2
#         j2 = j2+x.size-(i+1)
# y

In [12]:
j2 = 0
y = np.zeros_like(x)
for i in range(-1,3):
    j1 = j2
    j2 += x.size-np.abs(i)
    y += mf.matvec_diagk_prod(b[j1:j2],i,x)
#     print i, j1, j2, b[j1:j2], y
print y

[16. 30. 47. 48. 46.]


In [13]:
y = mf.matvec_band_opt_prod(b,x)
y

array([16., 30., 47., 48., 46.])

In [14]:
# y_calc = mf.matvec_symm_opt_prod(s, x)
# y_calc

In [15]:
# npt.assert_almost_equal(y_calc,y,decimal=15)