### Triangular matrices - Part 1

In [1]:
import numpy as np
import my_functions as mf
import numpy.testing as npt

In [2]:
x = np.array([1.,2.,1.,4.,6.])
print x

[1. 2. 1. 4. 6.]


In [3]:
# A = 10.*np.random.rand(5,5)
# A
A = np.ones((5,5))
A

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [4]:
U = np.triu(A)
U

array([[1., 1., 1., 1., 1.],
       [0., 1., 1., 1., 1.],
       [0., 0., 1., 1., 1.],
       [0., 0., 0., 1., 1.],
       [0., 0., 0., 0., 1.]])

### Algorithm 3

In [5]:
y = np.zeros_like(x)
for i in range(x.size):
    y[i] = mf.dot(U[i,i:],x[i:])
y

array([14., 13., 11., 10.,  6.])

In [6]:
y = mf.matvec_triu_prod3(U, x)
y

array([14., 13., 11., 10.,  6.])

### Algorithm 5

In [7]:
y = np.zeros_like(x)
for j in range(x.size):
    y[:j+1] += U[:j+1,j]*x[j]
y

array([14., 13., 11., 10.,  6.])

In [8]:
y = mf.matvec_triu_prod5(U, x)
y

array([14., 13., 11., 10.,  6.])

### Algorithm 8

In [9]:
L = np.tril(A)
z = np.zeros_like(x)
for i in range(x.size):
    z[i] = mf.dot(L[i,:i+1],x[:i+1])
z

array([ 1.,  3.,  4.,  8., 14.])

In [10]:
z = mf.matvec_tril_prod8(L, x)
z

array([ 1.,  3.,  4.,  8., 14.])

### Algorithm 10

In [11]:
z = np.zeros_like(x)
for j in range(x.size):
    z[j:] += L[j:,j]*x[j]
z

array([ 1.,  3.,  4.,  8., 14.])

In [12]:
z = mf.matvec_tril_prod10(L, x)
z

array([ 1.,  3.,  4.,  8., 14.])