### Triangular matrices - Part 2

In [1]:
import numpy as np
import my_functions as mf
import numpy.testing as npt

In [2]:
x = np.array([1.,2.,1.,4.,6.])
print x

[1. 2. 1. 4. 6.]


In [3]:
A = np.ones((5,5))
A

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [4]:
U = np.triu(A)
U

array([[1., 1., 1., 1., 1.],
       [0., 1., 1., 1., 1.],
       [0., 0., 1., 1., 1.],
       [0., 0., 0., 1., 1.],
       [0., 0., 0., 0., 1.]])

### First exercise

In [5]:
u = np.reshape(U, (U.shape[0]*U.shape[1]))
ind = np.where(u == 0.)[0]
u = np.delete(u, ind)
u

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [6]:
y = np.zeros(x.size)
k = 0
for i in range(x.size):
    y[:x.size-i] += u[i+k:x.size+k]*x[i:]
    k = x.size-(i+1)
y

array([14., 13., 11., 10.,  6.])

In [7]:
y = mf.matvec_triu_opt_prod(u, x)
y

array([14., 13., 11., 10.,  6.])

### Second exercise

In [8]:
L = np.tril(A)
L

array([[1., 0., 0., 0., 0.],
       [1., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0.],
       [1., 1., 1., 1., 1.]])

In [9]:
l = np.reshape(L, (L.shape[0]*L.shape[1]))
ind = np.where(l == 0.)[0]
l = np.delete(l, ind)
l

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [10]:
y = np.zeros(x.size)
k = 0
for i in range(x.size):
    y[x.size-i-1:] += l[k:i+k+1]*x[:i+1]
    k += i+1
y

array([ 1.,  3.,  4.,  8., 14.])

In [11]:
y = mf.matvec_tril_opt_prod(l, x)
y

array([ 1.,  3.,  4.,  8., 14.])