### Vector norms

Definition

let x be a $N \times 1$ vector given by:
\begin{equation}
\mathbf{x} = 
\begin{bmatrix}
x_1 \\ x_2 \\ \vdots \\ x_N
\end{bmatrix}
\end{equation}

The called *p-norms* are functions as follows:
\begin{equation}
\mathbf{f}_p(\mathbf{x}) = \parallel \mathbf{x} \parallel_p =
\left( |x_1|^p + \cdots + |x_N|^p\right)^{1/p}, \qquad p \geq 1
\end{equation}

In [1]:
import numpy as np
import my_functions as mf

In [2]:
def vec_norm(x, p):
    '''Calculates the p-norm of a vector
    
    input >
    x:    1D array - vector
    p:    int      - p value
    
    output >
    norm: scalar function
    '''
    assert type(p) == int, 'p value is not an integer'
    assert 0 <= p <= 2, 'p value must be in the inteval [0,2]'
    assert 0 <= p <= 2, 'p value must be in the inteval [0,2]'
    if p == 0:
        norm = np.max(x)
    elif p == 1:
        norm = np.sum(np.abs(x))
    else:
        norm = np.sqrt(mf.dot(x,x))
    return norm

In [3]:
x = np.arange(-2,3)
x

array([-2, -1,  0,  1,  2])

In [9]:
y = np.linspace(2,8,5)
y

array([2. , 3.5, 5. , 6.5, 8. ])

In [4]:
n = vec_norm(x, 0)
n

2

In [5]:
n = vec_norm(x, 1)
n

6

In [6]:
n = vec_norm(x, 2)
n

3.1622776601683795

In [7]:
n = vec_norm(x, -1)
n

AssertionError: p value must be in the inteval [0,2]

In [8]:
import numpy.testing as npt

In [10]:
x = np.arange(-2,3)
y = np.linspace(2,8,5)
print x
print y

[-2 -1  0  1  2]
[2.  3.5 5.  6.5 8. ]


In [11]:
n1 = vec_norm(x+y,2)
n1

13.693063937629153

In [12]:
n2 = vec_norm(x,2)
n2

3.1622776601683795

In [13]:
n3 = vec_norm(y,2)
n3

12.144957801491119

In [14]:
n2+n3 > n1

True