### Matrix and vector operations

In [1]:
import numpy as np

In [2]:
A = np.array([[1,2,3], [4,5,6],[7,8,9]])
print A, A.shape

[[1 2 3]
 [4 5 6]
 [7 8 9]] (3, 3)


In [3]:
x = np.ones(3)
print x, x.shape

[1. 1. 1.] (3,)


In [4]:
y = np.zeros_like(x)
y

array([0., 0., 0.])

In [5]:
N = 3
M = 3
for i in range(N):
    for j in range(M):
        y[i] += A[i,j]*x[j]
        print i,j,y
print y.shape

0 0 [1. 0. 0.]
0 1 [3. 0. 0.]
0 2 [6. 0. 0.]
1 0 [6. 4. 0.]
1 1 [6. 9. 0.]
1 2 [ 6. 15.  0.]
2 0 [ 6. 15.  7.]
2 1 [ 6. 15. 15.]
2 2 [ 6. 15. 24.]
(3,)


In [6]:
y = np.zeros_like(x)
for i in range(N):
    y[i] = np.dot(A[i,:],x)
    print i,j,y
print y, y.shape

0 2 [6. 0. 0.]
1 2 [ 6. 15.  0.]
2 2 [ 6. 15. 24.]
[ 6. 15. 24.] (3,)


In [7]:
y = np.zeros_like(x)
for j in range(M):
    y += A[:,j]*x[j]
    print i,j,y
print y, y.shape

2 0 [1. 4. 7.]
2 1 [ 3.  9. 15.]
2 2 [ 6. 15. 24.]
[ 6. 15. 24.] (3,)
